ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.pioneer.HttpKt.configureHttp
      - com.pioneer.SerializationKt.configureSerialization
      - com.pioneer.DatabaseMigrationsKt.configureDatabaseMigrations
      - com.pioneer.StatusPagesKt.configureStatusPages
      - com.pioneer.RoutingKt.configureRouting
      - com.pioneer.controller.map.MapModuleKt.configureMapController
      - com.pioneer.controller.auth.UserModuleKt.configureUserController
db:
  postgres:
    locationsTable: locations
